### ISSUE TITLE
Status Code 400 instead of 412

### ISSUE THREAD

**Issue by t1** [microprofile-extensions/jaxrs-ext#1]
Status code [412 Precondition Failed](https://tools.ietf.org/html/rfc7232#section-4.2) is defined for the very specific use-case of optimistic locking, i.e. when checking one of the `If-...` headers.
The status code [422 Unprocessable Entity](https://tools.ietf.org/html/rfc4918#section-11.2) would be more appropriate... or a generic [400 Bad Request](https://tools.ietf.org/html/rfc7231#section-6.5.1).

**Comment by phillip-kruger** [comment]
Hi ! Thanks for the issue. Mapping response codes correctly is very tricky ! Changing this now would be a breaking change. How about making it configurable (so the user can decide what code to map to) with the default still 412, so it's backward compatible. What do you think ?

**Comment by t1** [comment]
Yeah, people claiming REST was simple have absolutely no idea ;-)
Changing the result code _could_ break some things, you're right. I have no idea as to how much code actually relies on this specific error code, but it's at least theoretically possible.
OTOH it _might_ be that some tools (client apis, service meshes, maybe more) will misunderstand or even block a 412, but that's also just theory.
I don't really like to have to configure something to make it standards compliant, though. Maybe go to a version 2.0 instead, with this change well documented?

**Comment by phillip-kruger** [comment]
We are in the process of moving this (microprofile-ext) to smallrye, so as part of that I can change it. Still maybe making it configurable but let the default be 422. How does that sound ?

**Comment by phillip-kruger** [comment]
@t1 - Made the change here (as described above). It will more like this to smallrye. However we can release a new version here if you need it. Let me know

**Comment by t1** [comment]
That looks fine! And I don't need a extra release here :-)
